version: "3"

services:
  nbxplorer:
    container_name: nbxplorer
    ports: 
      - 32838:32838
    expose:
      - 32838
    build:
      context: .
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: 1
      NBXPLORER_BTCRPCURL: http://bitcoind-main:49372/
      NBXPLORER_BTCRPCUSER: ceiwHEbqWI83
      NBXPLORER_BTCRPCPASSWORD: DwubwWsoo3
      NBXPLORER_BTCNODEENDPOINT: bitcoind-main:8332
    links:
      - bitcoind-main

  bitcoind-main:
    build:
      context: ../docker-bitcoin
    container_name: bitcoind-main
    environment:
      BITCOIN_RPC_USER: ceiwHEbqWI83
      BITCOIN_RPC_PASSWORD: DwubwWsoo3
    expose:
      - "49372"
      - "8332"
    ports:
      - 49372:49372
      - 8332:8332
